# PostgreSQL 10

default: &default
  adapter: postgresql
  host: localhost
  username: piggy
  password: piggy_pass

production:
  <<: *default
  database: piggy_prod

development:
  <<: *default
  database: piggy_dev

test:
  <<: *default
  database: piggy_test
