# PostgreSQL 10

default: &default
  adapter: postgresql
  host: localhost
  username: piggy
  password: piggy_pass

development:
  <<: *default
  database: piggy

test:
  <<: *default
  database: piggy_test
